spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/local
    username: sa
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always


